spring:
  datasource:
    url: jdbc:h2:file:./tododb
    driverClassName: org.h2.Driver
    username: sa
    password: root
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop