create table public.users (
  id bigint generated by default as identity,
  link varchar(255) not null,
  username varchar(255) not null,
  primary key (id)
);

create table public.tasks (
    id bigint generated by default as identity,
    created_at date,
    description varchar(255),
    is_completed boolean not null,
    priority integer not null,
    title varchar(255) not null,
    user_id bigint,
    primary key (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

INSERT INTO public.users (username, link) VALUES ('nokisssev', 't.me/nokisssev');

INSERT INTO public.tasks (title, description, priority, is_completed, user_id) VALUES
('Доделать CI и написать нормальные тесты', 'Использовать github actions и junit 5', 2, true, 1),
('Подключить брокер сообщений', 'Например Apache Kafka', 1, false, 1);